spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message_demo_db?serverTimezone=Asia/Shanghai
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
